### PR TITLE
Fix for #39 - JQuery 3.1 compatibility

### LINKED ISSUE #39: Poptrox doesn't work with jQuery 3.1.0
After clicking on an image, I get the following errors"

```
TypeError: a.indexOf is not a function
r.fn.load()
 jquery.min.js:4
e.fn.poptrox/<()
 jquery.poptrox.min.js:2
r.event.dispatch()
 jquery.min.js:3
r.event.add/q.handle()
 jquery.min.js:3
.trigger()
 jquery.min.js:4
.trigger/<()
 jquery.min.js:4
.each()
 jquery.min.js:2
r.prototype.each()
 jquery.min.js:2
.trigger()
 jquery.min.js:4
e.fn.poptrox/</<()
 jquery.poptrox.min.js:2
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.fireWith()
 jquery.min.js:2
gb/i()
 jquery.min.js:3
r.fx.tick()
 jquery.min.js:3
ab()
 jquery.min.js:3
 jquery.min.js:4:18715
```

And after a while

```
too much recursion
.camelCase()
 jquery.min.js:2
U.prototype.get()
 jquery.min.js:3
.trigger()
 jquery.min.js:4
.trigger/<()
 jquery.min.js:4
.each()
 jquery.min.js:2
r.prototype.each()
 jquery.min.js:2
.trigger()
 jquery.min.js:4
e.fn.poptrox/</</<()
 jquery.poptrox.min.js:2
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
```

### PR DESCRIPTION
**Pull request by ChrisPuissant**
Fixes #39 replace .load() by .on("load") for JQuery 3.1 compatibility

### CODE REVIEW

**Comment by slurdge** [comment]
Please merge that one, so we can use cdnjs.com as a source
