### ISSUE TITLE
Poptrox doesn't work with jQuery 3.1.0

### ISSUE THREAD

**Issue by marmistrz** [n33/jquery.poptrox#39]
After clicking on an image, I get the following errors"

```
TypeError: a.indexOf is not a function
r.fn.load()
 jquery.min.js:4
e.fn.poptrox/<()
 jquery.poptrox.min.js:2
r.event.dispatch()
 jquery.min.js:3
r.event.add/q.handle()
 jquery.min.js:3
.trigger()
 jquery.min.js:4
.trigger/<()
 jquery.min.js:4
.each()
 jquery.min.js:2
r.prototype.each()
 jquery.min.js:2
.trigger()
 jquery.min.js:4
e.fn.poptrox/</<()
 jquery.poptrox.min.js:2
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.fireWith()
 jquery.min.js:2
gb/i()
 jquery.min.js:3
r.fx.tick()
 jquery.min.js:3
ab()
 jquery.min.js:3
 jquery.min.js:4:18715
```

And after a while

```
too much recursion
.camelCase()
 jquery.min.js:2
U.prototype.get()
 jquery.min.js:3
.trigger()
 jquery.min.js:4
.trigger/<()
 jquery.min.js:4
.each()
 jquery.min.js:2
r.prototype.each()
 jquery.min.js:2
.trigger()
 jquery.min.js:4
e.fn.poptrox/</</<()
 jquery.poptrox.min.js:2
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
 jquery.min.js:3
r.speed/e.complete()
 jquery.min.js:3
r.Callbacks/i()
 jquery.min.js:2
r.Callbacks/j.add()
 jquery.min.js:2
gb()
 jquery.min.js:3
.animate/g()
 jquery.min.js:3
.dequeue()
```

**Comment by flinhong** [comment]
Just found this answer: [http://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error](http://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error)

update all

``` js
$x.load(function() {});
```

to

``` js
$x.on('load', function() {});
```

This works for me using `jquery-3.1.1`.

**Comment by ajlkn** [comment]
Yup, what @flinhong said. There's a lot of legacy crap in Poptrox (it's an old plugin), so I'm probably just going to rewrite the entire thing.
